export enum Languages {
  af = 'Afrikaans',
  ak = 'Akan',
  am = 'አማርኛ', // Amharic
  ar = 'العربية', // Arabic
  as = 'Assamese',
  ay = 'Aymara',
  az = 'Azərbaycan dili', // Azerbaijani
  be = 'Беларуская', // Belarusian
  bg = 'български', // Bulgarian
  bho = 'Bhojpuri',
  bm = 'Bambara',
  bn = 'বাংলা', // Bengali
  bs = 'bosanski', // Bosnian
  ca = 'català', // Catalan
  ceb = 'Cebuano',
  ckb = 'Kurdî (Soranî)', // Kurdish (Sorani)
  co = 'Corse', // Corsican
  cs = 'čeština', // Czech
  cy = 'Cymraeg', // Welsh
  da = 'Dansk', // Danish
  de = 'Deutsch', // German
  doi = 'Dogri',
  dv = 'Divehi',
  ee = 'Ewe',
  el = 'Ελληνικά', // Greek
  en = 'English',
  eo = 'Esperanto',
  es = 'español', // Spanish
  et = 'eesti', // Estonian
  eu = 'euskara', // Basque
  fa = 'فارسی', // Persian
  fi = 'suomi', // Finnish
  fil = 'Filipino',
  fr = 'Français', // French
  fy = 'Frysk', // Frisian
  ga = 'Gaeilge', // Irish
  gd = 'Gàidhlig', // Scots Gaelic
  gl = 'galego', // Galician
  gn = 'Guarani',
  gom = 'Goan Konkani',
  gu = 'ગુજરાતી', // Gujarati
  ha = 'Hausa',
  haw = 'Hawaiʻi', // Hawaiian
  he = 'עברית', // Hebrew
  hi = 'हिन्दी', // Hindi
  hmn = 'Hmong',
  hr = 'hrvatski', // Croatian
  ht = 'Kreyòl Ayisyen', // Haitian Creole
  hu = 'magyar', // Hungarian
  hy = 'հայերեն', // Armenian
  id = 'Indonesia', // Indonesian
  ig = 'Igbo',
  ilo = 'Iloko',
  is = 'íslenska', // Icelandic
  it = 'Italiano', // Italian
  ja = '日本語', // Japanese
  jv = 'Javanese',
  ka = 'ქართული', // Georgian
  kk = 'қазақ', // Kazakh
  km = 'ខ្មែរ', // Khmer
  kn = 'ಕನ್ನಡ', // Kannada
  ko = '한국어', // Korean
  kri = 'Krio',
  ku = 'Kurdî (Kurmancî)', // Kurdish (Kurmanji)
  ky = 'кыргызча', // Kyrgyz
  la = 'Latin',
  lb = 'Lëtzebuergesch', // Luxembourgish
  lg = 'Ganda',
  ln = 'Lingala',
  lo = 'ລາວ', // Lao
  lt = 'lietuvių', // Lithuanian
  lus = 'Mizo',
  lv = 'latviešu', // Latvian
  mai = 'मैथिली', // Maithili
  mg = 'Malagasy',
  mi = 'Māori', // Maori
  mk = 'македонски', // Macedonian
  ml = 'മലയാളം', // Malayalam
  mn = 'Монгол', // Mongolian
  'mni-Mtei' = 'Manipuri (Meitei Mayek)',
  mr = 'मराठी', // Marathi
  ms = 'Bahasa Melayu', // Malay
  mt = 'Malti', // Maltese
  my = 'မြန်မာ', // Myanmar (Burmese)
  nb = 'norsk (bokmål)', // Norwegian (Bokmål)
  ne = 'नेपाली', // Nepali
  nl = 'Nederlands', // Dutch
  no = 'norsk', // Norwegian
  nso = 'Northern Sotho',
  ny = 'Chichewa',
  om = 'Oromo',
  or = 'Odia (Oriya)',
  pa = 'ਪੰਜਾਬੀ', // Punjabi
  pl = 'polski', // Polish
  ps = 'پښتو', // Pashto
  pt = 'Portuguese',
  qu = 'Quechua',
  ro = 'Română', // Romanian
  ru = 'русский', // Russian
  rw = 'Ikinyarwanda', // Kinyarwanda
  sa = 'Sanskrit',
  sd = 'سنڌي', // Sindhi
  si = 'සිංහල', // Sinhala
  sk = 'slovenčina', // Slovak
  sl = 'slovenščina', // Slovenian
  sm = 'Samoan',
  sn = 'ChiShona', // Shona
  so = 'Soomaali', // Somali
  sq = 'Shqip', // Albanian
  sr = 'српски', // Serbian
  ss = 'Swazi',
  st = 'Sesotho',
  su = 'Basa Sunda', // Sundanese
  sv = 'svenska', // Swedish
  sw = 'Kiswahili', // Swahili
  ta = 'தமிழ்', // Tamil
  te = 'తెలుగు', // Telugu
  tg = 'Тоҷикӣ', // Tajik
  th = 'ไทย', // Thai
  ti = 'Tigrinya',
  tk = 'Türkmençe', // Turkmen
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  tl = 'Filipino',
  tn = 'Setswana',
  tr = 'Türkçe', // Turkish
  ts = 'Tsonga',
  tt = 'Tatar',
  ug = 'Uyghur',
  uk = 'українська', // Ukrainian
  ur = 'اردو', // Urdu
  uz = 'O‘zbek', // Uzbek
  ve = 'Venda',
  vi = 'Việt', // Vietnamese
  xh = 'IsiXhosa', // Xhosa
  yi = 'יידיש', // Yiddish
  yo = 'Èdè Yorùbá', // Yoruba
  zh = '中文', // Chinese
  zu = 'isiZulu', // Zulu
}
